<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework Condition="'$(OS)' == 'Windows_NT'">net8.0-windows</TargetFramework>
    <TargetFramework Condition="'$(OS)' != 'Windows_NT'">net8.0</TargetFramework>
    <UseWindowsForms Condition="'$(OS)' == 'Windows_NT'">true</UseWindowsForms>
    <DefineConstants Condition="'$(OS)' == 'Windows_NT'">$(DefineConstants);WINDOWS_DESKTOP</DefineConstants>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.20" />
  </ItemGroup>
</Project>
